/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "movecraft-parent"
include(":movecraft-v1_19_r3")
include(":movecraft-v1_14_r1")
include(":movecraft-v1_18_r2")
include(":movecraft-v1_17_r1")
include(":movecraft-v1_16_r3")
include(":movecraft-api")
project(":movecraft-v1_19_r3").projectDir = file("modules/v1_19_R3")
project(":movecraft-v1_14_r1").projectDir = file("modules/v1_14_R1")
project(":movecraft-v1_18_r2").projectDir = file("modules/v1_18_R2")
project(":movecraft-v1_17_r1").projectDir = file("modules/v1_17_R1")
project(":movecraft-v1_16_r3").projectDir = file("modules/v1_16_R3")
project(":movecraft-api").projectDir = file("modules/api")
maven("https://jitpack.io")
compileOnly("com.github.oraxen:oraxen:1.156.2")
