/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("net.countercraft.java-conventions")
}

dependencies {
    api(project(":movecraft-api"))
    compileOnly("org.spigotmc:spigot:1.17.1-R0.1-SNAPSHOT")
}

description = "Movecraft-v1_17_R1"
